DOMAIN = "zyxel_lte5398_m904"
SENSOR = "sensor"

TITLE = "ZyXEL LTE5398-M904"

MANUFACTURER = "ZyXEL"

CONF_IP_ADDRESS = "ip_address"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

CONF_NAME = "name"
CONF_MODEL = "model"
CONF_SW_VERSION = "sw_version"

ZYXEL_SENSOR_RSRP ="RSRP"
ZYXEL_SENSOR_RSRQ = "RSRQ"
ZYXEL_SENSOR_SINR = "SINR"
ZYXEL_SENSOR_ACCESS_TECH = "Access_Technology"
ZYXEL_SENSOR_CELL_ID = "Cell ID"
ZYXEL_SENSOR_PHY_CELL_ID = "Physical Cell ID"
ZYXEL_SENSOR_ENB = "eNodeB"
ZYXEL_SENSOR_MAIN_BAND = "Main Band"
ZYXEL_SENSOR_CA_BANDS = "Carrier Aggregated Bands"